import { describe, it, expect, beforeEach, vi } from "vitest";
import { ShieldedVerifier } from "../src/verifier.js";
import { verifyECDSAP256 } from "../src/crypto.js";
import { RegistryClient } from "../src/registry.js";

// Import utility functions directly
import {
  ensureRandomUUID,
  randomNonce,
  buildProofLink,
  findSigningKey,
  computeAssuranceLevel,
  validateClaimValues,
  validateMinimalDisclosure,
  validateClaimsAgainstRequest,
  hasForbiddenEvidence,
  isNotExpired
} from "../src/verifier.js";

// The hardened verifier verifies REAL issuer-bound Bulletproofs. In this SDK
// unit suite we mock the WASM verification layer so we can test the verifier's
// policy, trust-chain, disclosure and error-handling logic in isolation. The
// genuine cryptographic round trip (real Bulletproof via the WASM) is covered
// by packages/age-zk/tests and apps/registry-server/tests/e2e-real.test.ts.
// Note we mock verify_ge/verify_le to RETURN TRUE ONLY, never to fabricate a
// pass for a malformed proof: every fail-closed path below is asserted against
// the verifier's own binding checks (commitment, issuer, signature, operator,
// context, nonce, expiry), which run before the ZK verdict.
vi.mock('@shielded-id/age-zk', () => ({
  prove_ge: vi.fn().mockImplementation(async () => {
    throw new Error("unused in this suite");
  }),
  prove_le_attested: vi.fn().mockResolvedValue({
    commitment: new Uint8Array(32).fill(1),
    proof: new Uint8Array(670).fill(2),
    public_inputs: new TextEncoder().encode("9000|18|https://shop.example|nonce|expiry")
  }),
  prove_ge_attested: vi.fn().mockResolvedValue({
    commitment: new Uint8Array(32).fill(3),
    proof: new Uint8Array(670).fill(4),
    public_inputs: new TextEncoder().encode("2|2|https://shop.example|nonce|expiry")
  }),
  verify_ge_components: vi.fn().mockResolvedValue(false),
  verify_le_components: vi.fn().mockResolvedValue(false),
  source_commitment_from_public_inputs: vi.fn().mockImplementation(async (pi: Uint8Array) => {
    // Return a stable commitment that matches the attestation fixture when the
    // proof was generated by the same helper used in this suite.
    return new TextDecoder().decode(pi).includes("|9000|")
      ? new Uint8Array(32).fill(1)
      : new Uint8Array(32).fill(3);
  })
}));

// Mock the crypto functions to avoid signature verification issues
vi.mock("../src/crypto.js", async () => {
  const actual = await vi.importActual("../src/crypto.js");
  return {
    ...actual,
    verifyECDSAP256: vi.fn().mockResolvedValue(true),
    validateNonce: vi.fn().mockImplementation((nonce1, nonce2) => nonce1 === nonce2),
    validateTimestamp: vi.fn().mockImplementation((issuedAt, expiresAt, maxAge) => {
      const now = Date.now();
      const issued = Date.parse(issuedAt);
      const expires = Date.parse(expiresAt);
      return now >= issued && now <= expires;
    })
  };
});

// Mock the registry client with the hardened shapes.
vi.mock("../src/registry.js", () => ({
  RegistryClient: vi.fn().mockImplementation(() => ({
    getKeyStatusViaNewEndpoint: vi.fn().mockResolvedValue({ revoked: false, expired: false }),
    getWalletStatus: vi.fn().mockImplementation((walletId: string) => {
      if (walletId === "unknown-wallet" || walletId === "non-existent-wallet") {
        return Promise.resolve(null);
      }
      if (walletId === "wallet-no-key" || walletId === "test-wallet-no-keys") {
        return Promise.resolve({ walletId, status: "ACTIVE", keys: [] });
      }
      if (walletId === "test-wallet-revoked-keys") {
        return Promise.resolve({
          walletId,
          status: "ACTIVE",
          keys: [{ keyId: "test-key", publicKey: { kty: "EC", crv: "P-256" }, status: "REVOKED" }]
        });
      }
      return Promise.resolve({
        walletId: "test-wallet",
        status: "ACTIVE",
        keys: [{ keyId: "test-key", publicKey: { kty: "EC", crv: "P-256" }, status: "ACTIVE" }]
      });
    }),
    getIssuerKey: vi.fn().mockImplementation((issuerDid: string) => {
      if (issuerDid === "did:example:missing-key" || issuerDid === "did:example:revoked-issuer") {
        throw new Error("ISSUER_KEY_NOT_FOUND");
      }
      return Promise.resolve({
        issuerDid,
        keyId: "issuer-key-1",
        status: "ACTIVE",
        publicKey: { kty: "EC", crv: "P-256" },
        createdAt: "2024-01-01T00:00:00Z"
      });
    }),
    resetCircuitBreaker: vi.fn()
  }))
}));

let verifier: ShieldedVerifier;

beforeEach(() => {
  verifier = new ShieldedVerifier({
    origin: "https://shop.example",
    registryUrl: "https://registry.example"
  });
  verifier.resetForTesting();
  vi.mocked(verifyECDSAP256).mockResolvedValue(true);
  const originalFetch = globalThis.fetch;
  globalThis.fetch = (async (url: string | Request | URL) => {
    const urlString = typeof url === "string" ? url : (url instanceof URL ? url.href : (url as Request).url);
    if (urlString.includes(".wasm")) return originalFetch(url);
    if (urlString.includes("/v1/status/") || urlString.match(/\/v1\/keys\/[^/]+\/status/) || urlString.includes("/v1/wallet/")) {
      if (urlString.includes("/v1/wallet/unknown-wallet")) {
        return { ok: false, status: 404, json: async () => ({ error: "Wallet not found" }) } as Response;
      }
      return {
        ok: true,
        status: 200,
        json: async () => ({
          walletId: "test-wallet",
          status: "ACTIVE",
          keys: [{ keyId: "test-key", publicKey: { kty: "EC", crv: "P-256" }, status: "ACTIVE" }]
        })
      } as Response;
    }
    if (urlString.includes("/v1/issuers/")) {
      if (urlString.includes("missing") || urlString.includes("revoked-issuer")) {
        return { ok: false, status: 404, json: async () => ({}) } as Response;
      }
      return {
        ok: true,
        status: 200,
        json: async () => ({
          issuerDid: "did:example:issuer",
          keyId: "issuer-key-1",
          status: "ACTIVE",
          publicKey: { kty: "EC", crv: "P-256" },
          createdAt: "2024-01-01T00:00:00Z"
        })
      } as Response;
    }
    return originalFetch(url);
  }) as typeof fetch;
});

function makeAttestation(attribute: "DOB_YYYYMMDD" | "KYC_LEVEL", issuerDid = "did:example:issuer") {
  return {
    version: "SID-COMMITMENT-1" as const,
    credentialId: "cred-1",
    attribute,
    commitment: Buffer.from(new Uint8Array(attribute === "DOB_YYYYMMDD" ? 32 : 32).fill(1)).toString("base64url"),
    issuerDid,
    keyId: "issuer-key-1",
    issuedAt: new Date(Date.now() - 1000).toISOString(),
    expiresAt: new Date(Date.now() + 60_000).toISOString(),
    signature: "mock-issuer-signature"
  };
}

describe("ShieldedVerifier", () => {
  it("creates proof requests with nonce and timestamps", () => {
    const request = verifier.createProofRequest({
      requestedClaims: [{ type: "AGE_OVER", operator: "LE", threshold: 18 }],
      policy: { requireStatusCheck: true, maxAgeSeconds: 60 },
      callback: { method: "POST", url: "https://shop.example/callback" }
    });

    expect(request.requestId).toBeTruthy();
    expect(request.nonce).toBeTruthy();
    expect(request.issuedAt).toBeTruthy();
    expect(request.expiresAt).toBeTruthy();
  });

  it("generates deep link", () => {
    const request = verifier.createProofRequest({
      requestedClaims: [{ type: "AGE_OVER", operator: "LE", threshold: 18 }],
      policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
      callback: { method: "POST", url: "https://shop.example/callback" }
    });

    const link = verifier.generateDeepLink(request);
    expect(link.startsWith("shielded-id://proof?")).toBe(true);
  });

  it("generates QR data URL", async () => {
    const request = verifier.createProofRequest({
      requestedClaims: [{ type: "AGE_OVER", operator: "LE", threshold: 18 }],
      policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
      callback: { method: "POST", url: "https://shop.example/callback" }
    });

    const qr = await verifier.generateQR(request);
    expect(qr.startsWith("data:image/png;base64,")).toBe(true);
  });
});

// Regression guardrails: Ensure minimal disclosure is maintained.
// The hardened verifier requires that AGE_OVER / KYC_LEVEL claims carry ONLY a
// boolean true value plus an issuer-bound commitment attestation — never the raw
// witness value. CONTINUITY must be a pairwise subject id string, never raw PII.
describe("Minimal Disclosure Regression Guards", () => {
  describe("AGE_OVER claims", () => {
    it("rejects proofs containing raw age values", async () => {
      const request = verifier.createProofRequest({
        requestedClaims: [{ type: "AGE_OVER", operator: "LE", threshold: 18 }],
        policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
        callback: { method: "POST", url: "https://shop.example/callback" }
      });

      const invalidProof = {
        requestId: request.requestId,
        nonce: request.nonce,
        walletId: "test-wallet",
        keyId: "test-key",
        pairwiseSubjectId: "test-subject-id-12345678",
        claims: [{ type: "AGE_OVER", value: 25 }], // ❌ Raw age value - forbidden
        suite: "ECDSA_P256_SHA256_1.0.0",
        signature: "mock-signature"
      };

      const result = await verifier.verifyProof(request, invalidProof);
      expect(result.valid).toBe(false);
      // A raw numeric value is rejected by claim-value validation (fail closed).
      expect(result.reason).toBe("INVALID_CLAIM_VALUE");
    });

    it("rejects proofs containing dateOfBirth", async () => {
      const request = verifier.createProofRequest({
        requestedClaims: [{ type: "AGE_OVER", operator: "LE", threshold: 18 }],
        policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
        callback: { method: "POST", url: "https://shop.example/callback" }
      });

      const invalidProof = {
        requestId: request.requestId,
        nonce: request.nonce,
        walletId: "test-wallet",
        keyId: "test-key",
        pairwiseSubjectId: "test-subjecture-12345678",
        claims: [{ type: "AGE_OVER", value: true, evidence: { dateOfBirth: "1990-01-01" } }],
        suite: "ECDSA_P256_SHA256_1.0.0",
        signature: "mock-signature"
      };

      const result = await verifier.verifyProof(request, invalidProof);
      expect(result.valid).toBe(false);
      expect(result.reason).toBe("MINIMAL_DISCLOSURE_VIOLATION");
    });
  });

  describe("KYC_LEVEL claims", () => {
    it("rejects proofs containing raw KYC level numbers", async () => {
      const request = verifier.createProofRequest({
        requestedClaims: [{ type: "KYC_LEVEL", operator: "GE", minLevel: 2 }],
        policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
        callback: { method: "POST", url: "https://shop.example/callback" }
      });

      const invalidProof = {
        requestId: request.requestId,
        nonce: request.nonce,
        walletId: "test-wallet",
        keyId: "test-key",
        pairwiseSubjectId: "test-subjecture-12345678",
        claims: [{ type: "KYC_LEVEL", value: 3 }], // ❌ Raw KYC level - forbidden
        suite: "ECDSA_P256_SHA256_1.0.0",
        signature: "mock-signature"
      };

      const result = await verifier.verifyProof(request, invalidProof);
      expect(result.valid).toBe(false);
      // A raw numeric value is rejected by claim-value validation (fail closed).
      expect(result.reason).toBe("INVALID_CLAIM_VALUE");
    });

    it("rejects proofs containing personal identifiers in evidence", async () => {
      const request = verifier.createProofRequest({
        requestedClaims: [{ type: "KYC_LEVEL", operator: "GE", minLevel: 2 }],
        policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
        callback: { method: "POST", url: "https://shop.example/callback" }
      });

      const invalidProof = {
        requestId: request.requestId,
        nonce: request.nonce,
        walletId: "test-wallet",
        keyId: "test-key",
        pairwiseSubjectId: "test-subjecture-12345678",
        claims: [{ type: "KYC_LEVEL", value: true, evidence: { ssn: "123-45-6789" } }],
        suite: "ECDSA_P256_SHA256_1.0.0",
        signature: "mock-signature"
      };

      const result = await verifier.verifyProof(request, invalidProof);
      expect(result.valid).toBe(false);
      expect(result.reason).toBe("MINIMAL_DISCLOSURE_VIOLATION");
    });
  });

  describe("CONTINUITY claims", () => {
    it("accepts a valid string pairwise subject ID (minimal disclosure)", async () => {
      const request = verifier.createProofRequest({
        requestedClaims: [{ type: "CONTINUITY" }],
        policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
        callback: { method: "POST", url: "https://shop.example/callback" }
      });

      const validProof = {
        requestId: request.requestId,
        nonce: request.nonce,
        walletId: "test-wallet",
        keyId: "test-key",
        pairwiseSubjectId: "test-subjecture-12345678",
        claims: [{ type: "CONTINUITY", value: "test-subjecture-12345678" }],
        suite: "ECDSA_P256_SHA256_1.0.0",
        signature: "mock-signature"
      };

      // The value must not fail on INVALID_CLAIM_VALUE or PII_DETECTED.
      const result = await verifier.verifyProof(request, validProof);
      expect(result.reason).not.toBe("INVALID_CLAIM_VALUE");
      expect(result.reason).not.toBe("PII_DETECTED");
      expect(result.reason).not.toBe("MINIMAL_DISCLOSURE_VIOLATION");
    });

    it("rejects a CONTINUITY value that is not a pairwise id", async () => {
      const request = verifier.createProofRequest({
        requestedClaims: [{ type: "CONTINUITY" }],
        policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
        callback: { method: "POST", url: "https://shop.example/callback" }
      });

      // A boolean true is NOT a valid pairwise subject id.
      const invalidProof = {
        requestId: request.requestId,
        nonce: request.nonce,
        walletId: "test-wallet",
        keyId: "test-key",
        pairwiseSubjectId: "test-subjecture-12345678",
        claims: [{ type: "CONTINUITY", value: true }],
        suite: "ECDSA_P256_SHA256_1.0.0",
        signature: "mock-signature"
      };

      const result = await verifier.verifyProof(request, invalidProof);
      expect(result.valid).toBe(false);
      expect(result.reason).toBe("INVALID_CLAIM_VALUE");
    });

    it("rejects a numeric CONTINUITY value", async () => {
      const request = verifier.createProofRequest({
        requestedClaims: [{ type: "CONTINUITY" }],
        policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
        callback: { method: "POST", url: "https://shop.example/callback" }
      });

      const invalidProof = {
        requestId: request.requestId,
        nonce: request.nonce,
        walletId: "test-wallet",
        keyId: "test-key",
        pairwiseSubjectId: "test-subjecture-12345678",
        claims: [{ type: "CONTINUITY", value: 123 }],
        suite: "ECDSA_P256_SHA256_1.0.0",
        signature: "mock-signature"
      };

      const result = await verifier.verifyProof(request, invalidProof);
      expect(result.valid).toBe(false);
      expect(result.reason).toBe("INVALID_CLAIM_VALUE");
    });
  });
});

describe("ShieldedVerifier Error Paths", () => {
  it("rejects expired requests", async () => {
    const expiredRequest = verifier.createProofRequest({
      requestedClaims: [{ type: "CONTINUITY" }],
      policy: { requireStatusCheck: true, maxAgeSeconds: 60 },
      callback: { method: "POST", url: "https://shop.example/callback" }
    });
    // Force the request to be expired.
    expiredRequest.expiresAt = new Date(Date.now() - 60_000).toISOString();

    const proof = {
      requestId: expiredRequest.requestId,
      nonce: expiredRequest.nonce,
      walletId: "test-wallet",
      keyId: "test-key",
      pairwiseSubjectId: "test-subjecture-12345678",
      claims: [{ type: "CONTINUITY", value: "test-subjecture-12345678" }],
      suite: "ECDSA_P256_SHA256_1.0.0",
      signature: "mock-signature"
    };

    const result = await verifier.verifyProof(expiredRequest, proof);
    expect(result.valid).toBe(false);
    expect(result.reason).toBe("REQUEST_EXPIRED");
  });

  it("rejects nonce mismatch", async () => {
    const request = verifier.createProofRequest({
      requestedClaims: [{ type: "CONTINUITY" }],
      policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
      callback: { method: "POST", url: "https://shop.example/callback" }
    });

    const proof = {
      requestId: request.requestId,
      nonce: "wrong-nonce",
      walletId: "test-wallet",
      keyId: "test-key",
      pairwiseSubjectId: "test-subjecture-12345678",
      claims: [{ type: "CONTINUITY", value: "test-subjecture-12345678" }],
      suite: "ECDSA_P256_SHA256_1.0.0",
      signature: "mock-signature"
    };

    const result = await verifier.verifyProof(request, proof);
    expect(result.valid).toBe(false);
    expect(result.reason).toBe("NONCE_MISMATCH");
  });

  it("rejects request ID mismatch", async () => {
    const request = verifier.createProofRequest({
      requestedClaims: [{ type: "CONTINUITY" }],
      policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
      callback: { method: "POST", url: "https://shop.example/callback" }
    });

    const proof = {
      requestId: "wrong-request-id",
      nonce: request.nonce,
      walletId: "test-wallet",
      keyId: "test-key",
      pairwiseSubjectId: "test-subjecture-12345678",
      claims: [{ type: "CONTINUITY", value: "test-subjecture-12345678" }],
      suite: "ECDSA_P256_SHA256_1.0.0",
      signature: "mock-signature"
    };

    const result = await verifier.verifyProof(request, proof);
    expect(result.valid).toBe(false);
    expect(result.reason).toBe("REQUEST_ID_MISMATCH");
  });

  it("rejects unsupported suite", async () => {
    const request = verifier.createProofRequest({
      requestedClaims: [{ type: "AGE_OVER", operator: "LE", threshold: 18 }],
      policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
      callback: { method: "POST", url: "https://shop.example/callback" }
    });
    const attestation = makeAttestation("DOB_YYYYMMDD");

    const proof = {
      requestId: request.requestId,
      nonce: request.nonce,
      walletId: "test-wallet",
      keyId: "test-key",
      pairwiseSubjectId: "test-subjecture-12345678",
      claims: [{
        type: "AGE_OVER", value: true, operator: "LE",
        issuer: { did: attestation.issuerDid, keyId: "issuer-key-1", signature: attestation.signature },
        expiresAt: attestation.expiresAt,
        evidence: { commitmentAttestation: attestation }
      }],
      suite: "UNSUPPORTED_SUITE",
      signature: "mock-signature"
    };

    const result = await verifier.verifyProof(request, proof);
    expect(result.valid).toBe(false);
    expect(result.reason).toBe("UNSUPPORTED_SUITE");
  });

  it("rejects a ZK request that omits the ZK proof", async () => {
    const request = verifier.createProofRequest({
      requestedClaims: [{ type: "AGE_OVER", operator: "LE", threshold: 18 }],
      policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
      callback: { method: "POST", url: "https://shop.example/callback" }
    });
    const attestation = makeAttestation("DOB_YYYYMMDD");

    const proof = {
      requestId: request.requestId,
      nonce: request.nonce,
      walletId: "test-wallet",
      keyId: "test-key",
      pairwiseSubjectId: "test-subjecture-12345678",
      claims: [{
        type: "AGE_OVER", value: true, operator: "LE",
        issuer: { did: attestation.issuerDid, keyId: "issuer-key-1", signature: attestation.signature },
        expiresAt: attestation.expiresAt,
        evidence: { commitmentAttestation: attestation }
      }],
      suite: "BULLETPROOFS_RISTRETTO_BOUND_V2",
      signature: "mock-signature"
    };

    const result = await verifier.verifyProof(request, proof);
    expect(result.valid).toBe(false);
    expect(result.reason).toBe("MISSING_ZK_PROOF");
  });

  it("rejects a non-ZK response that carries a ZK proof", async () => {
    const request = verifier.createProofRequest({
      requestedClaims: [{ type: "CONTINUITY" }],
      policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
      callback: { method: "POST", url: "https://shop.example/callback" }
    });

    const proof = {
      requestId: request.requestId,
      nonce: request.nonce,
      walletId: "test-wallet",
      keyId: "test-key",
      pairwiseSubjectId: "test-subjecture-12345678",
      claims: [{ type: "CONTINUITY", value: "test-subjecture-12345678" }],
      suite: "ECDSA_P256_SHA256_1.0.0",
      signature: "mock-signature",
      zkProofs: { 0: { claimType: "AGE_OVER", operator: "LE" } }
    };

    const result = await verifier.verifyProof(request, proof);
    expect(result.valid).toBe(false);
    expect(result.reason).toBe("UNEXPECTED_ZK_PROOF");
  });

  it("handles wallet not found", async () => {
    const request = verifier.createProofRequest({
      requestedClaims: [{ type: "CONTINUITY" }],
      policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
      callback: { method: "POST", url: "https://shop.example/callback" }
    });

    const proof = {
      requestId: request.requestId,
      nonce: request.nonce,
      walletId: "unknown-wallet",
      keyId: "test-key",
      pairwiseSubjectId: "test-subjecture-12345678",
      claims: [{ type: "CONTINUITY", value: "test-subjecture-12345678" }],
      suite: "ECDSA_P256_SHA256_1.0.0",
      signature: "mock-signature"
    };

    const result = await verifier.verifyProof(request, proof);
    expect(result.valid).toBe(false);
    expect(result.reason).toBe("WALLET_NOT_FOUND");
  });

  it("rejects a missing key ID when a status check is required", async () => {
    const request = verifier.createProofRequest({
      requestedClaims: [{ type: "CONTINUITY" }],
      policy: { requireStatusCheck: true, maxAgeSeconds: 60 },
      callback: { method: "POST", url: "https://shop.example/callback" }
    });

    const proof = {
      requestId: request.requestId,
      nonce: request.nonce,
      walletId: "test-wallet",
      pairwiseSubjectId: "test-subjecture-12345678",
      claims: [{ type: "CONTINUITY", value: "test-subjecture-12345678" }],
      suite: "ECDSA_P256_SHA256_1.0.0",
      signature: "mock-signature"
    };

    const result = await verifier.verifyProof(request, proof);
    expect(result.valid).toBe(false);
    expect(result.reason).toBe("MALFORMED_RESPONSE");
  });

  it("rejects expired claims", async () => {
    const request = verifier.createProofRequest({
      requestedClaims: [{ type: "CONTINUITY" }],
      policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
      callback: { method: "POST", url: "https://shop.example/callback" }
    });

    const proof = {
      requestId: request.requestId,
      nonce: request.nonce,
      walletId: "test-wallet",
      keyId: "test-key",
      pairwiseSubjectId: "test-subjecture-12345678",
      claims: [{ type: "CONTINUITY", value: "test-subjecture-12345678", expiresAt: "2020-01-01T00:00:00Z" }],
      suite: "ECDSA_P256_SHA256_1.0.0",
      signature: "mock-signature"
    };

    const result = await verifier.verifyProof(request, proof);
    expect(result.valid).toBe(false);
    expect(result.reason).toBe("CLAIM_EXPIRED");
  });
});

describe("ShieldedVerifier Methods", () => {
  it("checkRevocation method works", async () => {
    const result = await verifier.checkRevocation("test-key");
    expect(result).toBeDefined();
    expect(result.revoked).toBe(false);
  });

  it("rejects proofs when the wallet has no active signing key", async () => {
    const originalFetch = globalThis.fetch;
    globalThis.fetch = vi.fn().mockImplementation(async (url: string | Request | URL) => {
      const urlString = typeof url === "string" ? url : (url instanceof URL ? url.href : (url as Request).url);
      if (urlString.includes("/v1/status/wallet-no-key")) {
        return { ok: true, status: 200, json: async () => ({ walletId: "wallet-no-key", status: "ACTIVE", keys: [] }) } as Response;
      }
      return originalFetch(url);
    }) as typeof fetch;

    const request = verifier.createProofRequest({
      requestedClaims: [{ type: "CONTINUITY" }],
      policy: { requireStatusCheck: true, maxAgeSeconds: 60 },
      callback: { method: "POST", url: "https://shop.example/callback" }
    });

    const proof = {
      requestId: request.requestId,
      nonce: request.nonce,
      walletId: "wallet-no-key",
      keyId: "test-key",
      pairwiseSubjectId: "test-subjecture-12345678",
      claims: [{ type: "CONTINUITY", value: "test-subjecture-12345678" }],
      suite: "ECDSA_P256_SHA256_1.0.0",
      signature: "mock-signature"
    };

    const result = await verifier.verifyProof(request, proof);
    expect(result.valid).toBe(false);
    expect(result.reason).toBe("NO_ACTIVE_MATCHING_KEY");
  });

  it("rejects invalid wallet signatures", async () => {
    vi.mocked(verifyECDSAP256).mockResolvedValue(false);
    const request = verifier.createProofRequest({
      requestedClaims: [{ type: "CONTINUITY" }],
      policy: { requireStatusCheck: true, maxAgeSeconds: 60 },
      callback: { method: "POST", url: "https://shop.example/callback" }
    });

    const proof = {
      requestId: request.requestId,
      nonce: request.nonce,
      walletId: "test-wallet",
      keyId: "test-key",
      pairwiseSubjectId: "test-subjecture-12345678",
      claims: [{ type: "CONTINUITY", value: "test-subjecture-12345678" }],
      suite: "ECDSA_P256_SHA256_1.0.0",
      signature: "mock-signature"
    };

    const result = await verifier.verifyProof(request, proof);
    expect(result.valid).toBe(false);
    expect(result.reason).toBe("INVALID_WALLET_SIGNATURE");
  });

  it("rejects when issuer key is missing", async () => {
    const request = verifier.createProofRequest({
      requestedClaims: [{ type: "AGE_OVER", operator: "LE", threshold: 18 }],
      policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
      callback: { method: "POST", url: "https://shop.example/callback" }
    });

    const attestation = makeAttestation("DOB_YYYYMMDD", "did:example:missing");
    const proof = {
      requestId: request.requestId,
      nonce: request.nonce,
      walletId: "test-wallet",
      keyId: "test-key",
      pairwiseSubjectId: "test-subjecture-12345678",
      claims: [{
        type: "AGE_OVER",
        value: true,
        operator: "LE",
        issuer: { did: "did:example:missing", keyId: "issuer-key-1", signature: attestation.signature },
        expiresAt: attestation.expiresAt,
        evidence: { commitmentAttestation: attestation }
      }],
      suite: "BULLETPROOFS_RISTRETTO_BOUND_V2",
      signature: "mock-signature",
      zkProofs: { 0: { claimType: "AGE_OVER", operator: "LE", commitment: "cm", bulletproof: "bp", publicInputs: "pi" } }
    };

    const result = await verifier.verifyProof(request, proof, { checkRevocation: false });
    expect(result.valid).toBe(false);
  });

  it("rejects invalid issuer signatures", async () => {
    const request = verifier.createProofRequest({
      requestedClaims: [{ type: "AGE_OVER", operator: "LE", threshold: 18 }],
      policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
      callback: { method: "POST", url: "https://shop.example/callback" }
    });

    const attestation = makeAttestation("DOB_YYYYMMDD");
    attestation.signature = "tampered-issuer-signature";
    const proof = {
      requestId: request.requestId,
      nonce: request.nonce,
      walletId: "test-wallet",
      keyId: "test-key",
      pairwiseSubjectId: "test-subjecture-12345678",
      claims: [{
        type: "AGE_OVER",
        value: true,
        operator: "LE",
        issuer: { did: attestation.issuerDid, keyId: "issuer-key-1", signature: attestation.signature },
        expiresAt: attestation.expiresAt,
        evidence: { commitmentAttestation: attestation }
      }],
      suite: "BOUNDPROOFS_RISTRETTO_BOUND_V2",
      signature: "mock-signature",
      zkProofs: { 0: { claimType: "AGE_OVER", operator: "LE", commitment: "cm", bulletproof: "fp", publicInputs: "pi" } }
    };

    const result = await verifier.verifyProof(request, proof, { checkRevocation: false });
    expect(result.valid).toBe(false);
  });
});

describe("Utility Functions", () => {
  describe("findSigningKey", () => {
    it("returns null when no keys or no required keyId provided", () => {
      expect(findSigningKey(undefined, "k1")).toBeNull();
      expect(findSigningKey([], "k1")).toBeNull();
      // No required key id -> null (verifier never guesses a key).
      expect(findSigningKey([{ keyId: "k1", status: "ACTIVE", publicKey: { kty: "EC" } }])).toBeNull();
    });

    it("returns the active public key matching the required keyId", () => {
      const keys = [
        { keyId: "k1", status: "ACTIVE", publicKey: { kty: "EC" } }
      ];
      expect(findSigningKey(keys, "k1")).toEqual({ kty: "EC" });
    });

    it("returns null for a revoked key", () => {
      const keys = [
        { keyId: "k1", status: "REVOKED", publicKey: { kty: "EC" } }
      ];
      expect(findSigningKey(keys, "k1")).toBeNull();
    });

    it("returns null when the required keyId is not present", () => {
      const keys = [
        { keyId: "k1", status: "ACTIVE", publicKey: { kty: "EC" } }
      ];
      expect(findSigningKey(keys, "missing")).toBeNull();
    });
  });

  describe("computeAssuranceLevel", () => {
    it("returns the requested KYC min level when a KYC claim is satisfied", () => {
      const request = { requestedClaims: [{ type: "KYC_LEVEL", operator: "GE", minLevel: 3 }] } as never;
      const claims = [{ type: "KYC_LEVEL", value: true, operator: "GE" }] as never;
      expect(computeAssuranceLevel(claims, request)).toBe(3);
    });

    it("returns 0 when no KYC_LEVEL is requested", () => {
      const request = { requestedClaims: [{ type: "AGE_OVER", operator: "LE", threshold: 18 }] } as never;
      const claims = [{ type: "AGE_OVER", value: true, operator: "LE" }] as never;
      expect(computeAssuranceLevel(claims, request)).toBe(0);
    });
  });

  describe("validateClaimValues", () => {
    it("returns true for valid claims", () => {
      const claims = [
        { type: "AGE_OVER", value: true },
        { type: "KYC_LEVEL", value: true },
        { type: "CONTINUITY", value: "test-subjecture-12345678" }
      ];
      expect(validateClaimValues(claims)).toBe(true);
    });

    it("returns false for a raw AGE_OVER value", () => {
      expect(validateClaimValues([{ type: "AGE_OVER", value: "invalid" }])).toBe(false);
    });

    it("returns false for a numeric CONTINUITY value", () => {
      expect(validateClaimValues([{ type: "CONTINUITY", value: 123 }])).toBe(false);
    });
  });

  describe("validateMinimalDisclosure", () => {
    it("returns false for a claim without issuer-bound evidence", () => {
      expect(validateMinimalDisclosure([{ type: "AGE_OVER", value: true }])).toBe(false);
    });

    it("returns false for AGE_OVER with a non-boolean value", () => {
      expect(validateMinimalDisclosure([{ type: "AGE_OVER", value: 25 }])).toBe(false);
    });

    it("returns false for forbidden evidence fields", () => {
      expect(validateMinimalDisclosure([{ type: "AGE_OVER", value: true, evidence: { dateOfBirth: "1990-01-01" } }])).toBe(false);
    });
  });

  describe("validateClaimsAgainstRequest", () => {
    it("returns true for a matching AGE_OVER (LE) claim", () => {
      const requested = [{ type: "AGE_OVER", threshold: 18, operator: "LE" }];
      const claims = [{ type: "AGE_OVER", value: true, operator: "LE" }];
      expect(validateClaimsAgainstRequest(requested, claims)).toBe(true);
    });

    it("returns false when the operator is not LE for AGE_OVER", () => {
      const requested = [{ type: "AGE_OVER", threshold: 18, operator: "LE" }];
      const claims = [{ type: "AGE_OVER", value: true, operator: "GE" }];
      expect(validateClaimsAgainstRequest(requested, claims)).toBe(false);
    });

    it("returns false for an unsupported claim type", () => {
      const requested = [{ type: "COUNTRY", expectedValue: "US", operator: "EQ" } as never];
      const claims = [{ type: "COUNTRY", value: "US" } as never];
      expect(validateClaimsAgainstRequest(requested, claims)).toBe(false);
    });
  });

  describe("hasForbiddenEvidence", () => {
    it("returns false when no evidence", () => {
      const claim = { type: "AGE_OVER", value: true };
      expect(hasForbiddenEvidence(claim, ["forbidden"])).toBe(false);
    });

    it("returns true when evidence has forbidden fields", () => {
      const claim = { type: "AGE_OVER", value: true, evidence: { dateOfBirth: "1990-01-01" } };
      expect(hasForbiddenEvidence(claim, ["dateofbirth"])).toBe(true);
    });
  });

  describe("isNotExpired", () => {
    it("returns true for future expiry", () => {
      const futureDate = new Date(Date.now() + 3600000).toISOString();
      expect(isNotExpired(futureDate)).toBe(true);
    });

    it("returns false for past expiry", () => {
      const pastDate = new Date(Date.now() - 3600000).toISOString();
      expect(isNotExpired(pastDate)).toBe(false);
    });

    it("returns false for invalid date", () => {
      expect(isNotExpired("invalid-date")).toBe(false);
    });
  });
});

describe("Unsupported historical predicates fail closed", () => {
  // Predicates from the old fake architecture (STRING_EQUALS, MEMBERSHIP,
  // NOT_IN_LIST, PREFIX, AGE_RANGE, COUNTRY, etc.) are NOT cryptographically
  // implemented. The verifier must never accept a proof for them: verifyProof
  // fails closed (valid:false) rather than trusting a publicInputs claim.
  it("rejects createProofRequest with AGE_OVER using a non-LE operator", () => {
    const unsafe = () => verifier.createProofRequest({
      requestedClaims: [{ type: "AGE_OVER", operator: "GE", threshold: 18 } as never],
      policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
      callback: { method: "POST", url: "https://shop.example/callback" }
    });
    expect(unsafe).toThrow("AGE_OVER_OPERATOR_MUST_BE_LE");
  });

  it("rejects createProofRequest for KYC_LEVEL using a non-GE operator", () => {
    const unsafe = () => verifier.createProofRequest({
      requestedClaims: [{ type: "KYC_LEVEL", operator: "LE", minLevel: 2 } as never],
      policy: { requireStatusCheck: false, maxAgeSeconds: 60 },
      callback: { method: "POST", url: "https://shop.example/callback" }
    });
    expect(unsafe).toThrow("KYC_LEVEL_OPERATOR_MUST_BE_GE");
  });
});
